# Eureka client configuration
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# Zuul configuration
zuul:
  prefix: /api
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  routes:
    catalog:
      path: /catalog/**
      serviceId: catalog-service
    order:
      path: /order/**
      serviceId: order-service