# Ribbon configuration
#catalog-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9000,localhost:9001,localhost:9002
#    ServerListRefreshInterval: 15000
#
#order-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9100,localhost:9101
#    ServerListRefreshInterval: 15000


# Eureka client configuration
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# Feign client configuration
#catalog-service:
#  ribbon:
#    DeploymentContextBasedVipAddresses: catalog-service
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList


# Hystrix configuration
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 5000