# Ribbon load balancer configuration
catalog-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9000,localhost:9001,localhost:9002
    ServerListRefreshInterval: 15000


# Eureka client configuration
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Feign client configuration
#catalog-service:
#  ribbon:
#    DeploymentContextBasedVipAddresses: catalog-service
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList